### ISSUE TITLE
newestOnTop error on Angular 1.4

### ISSUE THREAD

**Issue by kuntau** [Foxandxss/angular-toastr#87]
Hello, this time I think is a real bug.

Options newestOnTop set to false won't work on angular 1.4. It work on angular 1.3 as in the demo site.

Demo plnkr: http://plnkr.co/KATVHGIuXggG2HneaEWO

    angular-toastr#1.3.0
    angular#1.4.0-rc.1

Here is the error I got.

```
TypeError: afterElement.after is not a function
    at domInsert (angular.js:4923)
    at Object.$AnimateProvider.$get.enter (angular.js:5084)
    at angular-toastr.tpls.min.js:1
    at processQueue (angular.js:14347)
    at angular.js:14363
    at Scope.$get.Scope.$eval (angular.js:15574)
    at Scope.$get.Scope.$digest (angular.js:15385)
    at Scope.$get.Scope.$apply (angular.js:15679)
    at angular.js:17435
    at completeOutstandingRequest (angular.js:5296)
```

**Comment by Foxandxss** [comment]
Yeah, since you reported the last bug, I started to test the library against 1.4 (I was waiting to the final release).

I saw that same issue and I am trying to squash it :)

Angular 1.4 changed ngAnimate a lot so there should be something different this time.

**Comment by Foxandxss** [comment]
I fixed it on master, will be up on the next version.
