### ISSUE TITLE
Error work on angular 1.4rc

### ISSUE THREAD

**Issue by kuntau** [Foxandxss/angular-toastr#86]
angular-toastr#1.3.0
    angular#1.4.0-rc.1

Here is the error I got.

```
TypeError: newToast.scope.init is not a function
    at angular-toastr.js:164
    at processQueue (angular.js:14347)
    at angular.js:14363
    at Scope.$get.Scope.$eval (angular.js:15574)
    at Scope.$get.Scope.$digest (angular.js:15385)
    at angular.js:15613
    at completeOutstandingRequest (angular.js:5296)
    at angular.js:5568(anonymous function) @ angular.js:12116$get @ angular.js:8976processQueue @ angular.js:14355(anonymous function) @ angular.js:14363$get.Scope.$eval @ angular.js:15574$get.Scope.$digest @ angular.js:15385(anonymous function) @ angular.js:15613completeOutstandingRequest @ angular.js:5296(anonymous function) @ angular.js:5568
angular.js:12116 Error: [$compile:tplrt] Template for directive 'toast' must have exactly one root element. directives/toast/toast.html
http://errors.angularjs.org/1.4.0-rc.1/$compile/tplrt?p0=toast&p1=directives%2Ftoast%2Ftoast.html
    at REGEX_STRING_REGEXP (angular.js:68)
    at angular.js:8206
    at processQueue (angular.js:14347)
    at angular.js:14363
    at Scope.$get.Scope.$eval (angular.js:15574)
    at Scope.$get.Scope.$digest (angular.js:15385)
    at Scope.$get.Scope.$apply (angular.js:15679)
    at done (angular.js:10166)
    at completeRequest (angular.js:10338)
    at XMLHttpRequest.requestLoaded (angular.js:10279)
```

**Comment by Foxandxss** [comment]
Let me research that, it is the second report I get today about that.

**Comment by Foxandxss** [comment]
In the meantime, can you give me more info? or even a repro in plunker.

Are you using the version without templates so I guess you're providing one, right? Can I see it?

**Comment by kuntau** [comment]
Coming from previous version I missed the part that I have to include the templated version. It work flawlessly now. Sorry.

**Comment by Foxandxss** [comment]
No worries. The .init method wasn't found because there is no template and the directive won't load.
